### ISSUE TITLE
Post lag

### ISSUE THREAD

**Issue by Dnkfff** [mezgoodle/meziblog#14] opened 2022-04-09 20:54 UTC
- [ ] When creating a new post with mountain image, it appears with alliance human on the main page

**Comment by mezgoodle** [comment] 2022-04-10 11:31
> * [ ]  When creating a new post with mountain image, it appears with alliance human on the main page

Good day! As you can see in the code([new.js](https://github.com/mezgoodle/meziblog/blob/master/frontend/pages/post/new.js#L41-L45), [Post.js](https://github.com/mezgoodle/meziblog/blob/master/frontend/components/Post.js#L12-L18)) images don't effect on the functionality. They exist only for design. In the [function](https://github.com/mezgoodle/meziblog/blob/master/frontend/pages/post/new.js#L15-L28) for creating posts, there is no word about images. In the model(_image below_) for creating post, there isn't field for the image path or something like this.
![image](https://user-images.githubusercontent.com/41520940/162615800-b9251717-ab15-4b80-a44c-8a72feaaf41c.png)
---
So it's not a bug, lag, lug or something else, I don't know.
If you haven't any questions, close this issue

And For the lady Sylvanas!
![image](https://steamuserimages-a.akamaihd.net/ugc/876377577853761227/E97C09849F36A9DD7D9C3385409B87006E290AE3/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

**Comment by Dnkfff** [comment] 2022-04-10 18:51
Sorry, but usually I do not use python. And there is one more problem with login/registration, you might have to fix your BACKEND problems...
![image](https://user-images.githubusercontent.com/56574536/162634999-ec620fe6-92d1-4ead-9772-3c112d6681d5.png)

**Comment by Dnkfff** [comment] 2022-04-10 18:52
I have a lot of questions about this app, and that is why I uploaded my issue, alliance is stronger...

**Comment by mezgoodle** [comment] 2022-04-11 06:48
> Sorry, but usually I do not use python. And there is one more problem with login/registration, you might have to fix your BACKEND problems... ![image](https://user-images.githubusercontent.com/56574536/162634999-ec620fe6-92d1-4ead-9772-3c112d6681d5.png)

There is no problems with the login/register page. I have checked it recently

**Comment by Dmytrenko-Roman** [comment] 2022-04-11 08:45
FOR THE GLORY OF THE WHIP!

<p align="center">![](https://raw.githubusercontent.com/Dmytrenko-Roman/pictures-gifs/main/gifs/arthas.ForAllREADMEs.gif)</p>

> I have a lot of questions about this app, and that is why I uploaded my issue, alliance is stronger...

**Closed** 2022-04-13 07:43 UTC
Labels: question
